#!/usr/bin/env python3
"""Deterministic baseline scanner for error-governance-hardgate."""

from __future__ import annotations

import argparse
import json
import os
import re
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

SKILL = "error-governance-hardgate"
SCHEMA_VERSION = "1.0.0"

TEXT_EXTS = {
    ".py", ".pyi", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".json", ".yaml", ".yml", ".toml", ".ini", ".md", ".mdx", ".rst",
}
CODE_EXTS = {".py", ".pyi", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"}
DOC_EXTS = {".md", ".mdx", ".rst"}
SKIP_DIRS = {
    ".git", ".hg", ".svn", ".venv", "venv", "__pycache__", "node_modules",
    "dist", "build", ".next", ".nuxt", ".turbo", ".cache", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", ".tox", "coverage", ".repo-harness",
    "vendor", "target", "out", ".idea", ".vscode", ".pooh-runtime",
}

OPENAPI_RE = re.compile(r"\bopenapi\b|\bswagger\b", re.IGNORECASE)
ASYNCAPI_RE = re.compile(r"\basyncapi\b", re.IGNORECASE)
PROBLEM_MEDIA_RE = re.compile(r"application/problem\+json", re.IGNORECASE)
PROBLEM_DETAILS_RE = re.compile(r"\bproblem details\b|problem\+json", re.IGNORECASE)
CORE_FIELD_RE = {
    "type": re.compile(r'["\']type["\']\s*[:=]|\btype:\s*https?://', re.IGNORECASE),
    "title": re.compile(r'["\']title["\']\s*[:=]', re.IGNORECASE),
    "status": re.compile(r'["\']status["\']\s*[:=]|\bstatus_code\b', re.IGNORECASE),
    "detail": re.compile(r'["\']detail["\']\s*[:=]', re.IGNORECASE),
    "instance": re.compile(r'["\']instance["\']\s*[:=]', re.IGNORECASE),
}
EXTENSION_FIELD_RE = {
    "code": re.compile(r'["\']code["\']\s*[:=]|\berror_code\b|\bproblem_code\b', re.IGNORECASE),
    "trace_id": re.compile(r"\btrace[_-]?id\b", re.IGNORECASE),
    "timestamp": re.compile(r"\btimestamp\b|\bdate-time\b", re.IGNORECASE),
    "service": re.compile(r'["\']service["\']\s*[:=]|\bservice[_-]?name\b', re.IGNORECASE),
    "retry_after_ms": re.compile(r"\bretry[_-]?after(?:_ms)?\b|\bRetry-After\b", re.IGNORECASE),
    "errors_array": re.compile(r'["\']errors["\']\s*:\s*\[', re.IGNORECASE),
}
PATH_SURFACE_RE = {
    "catalog": re.compile(r"(error[-_]?codes?|error[_-]?catalog|problem[-_]?types?)", re.IGNORECASE),
    "handler": re.compile(r"(error|exception|middleware|handler|filters?|responses?|api|routes?)", re.IGNORECASE),
    "generated": re.compile(r"(generated|openapi|asyncapi|sdk|client|types?)", re.IGNORECASE),
    "schema": re.compile(r"(schema|spec|contract|openapi|asyncapi)", re.IGNORECASE),
}
FRAMEWORK_RE = {
    "fastapi": re.compile(r"\bfastapi\b|\bAPIRouter\b", re.IGNORECASE),
    "flask": re.compile(r"\bflask\b|\bBlueprint\b", re.IGNORECASE),
    "django": re.compile(r"\bdjango\b|\bJsonResponse\b", re.IGNORECASE),
    "express": re.compile(r"\bexpress\b|\bres\.status\b", re.IGNORECASE),
    "nestjs": re.compile(r"\b@nestjs\b|\bHttpException\b", re.IGNORECASE),
}
GLOBAL_HANDLER_RE = [
    re.compile(r"\bapp\.exception_handler\b", re.IGNORECASE),
    re.compile(r"\badd_exception_handler\b", re.IGNORECASE),
    re.compile(r"\bExceptionMiddleware\b", re.IGNORECASE),
    re.compile(r"\b@Catch\b", re.IGNORECASE),
    re.compile(r"\bsetErrorHandler\b", re.IGNORECASE),
    re.compile(r"\berrorHandler\b", re.IGNORECASE),
]
TEXT_BRANCH_RE = [
    re.compile(r'if\s+["\'][^"\']+(?:not found|expired|forbidden|invalid|timeout)[^"\']*["\']\s+in\s+[A-Za-z0-9_.()\[\]]+', re.IGNORECASE),
    re.compile(r'\.(?:includes|contains|startswith|endswith)\(\s*["\'][^"\']+(?:not found|expired|forbidden|invalid|timeout)[^"\']*["\']\s*\)', re.IGNORECASE),
    re.compile(r'\b(?:detail|message|title)\b[^;\n]{0,80}\b(?:includes|contains|startswith|endswith)\(', re.IGNORECASE),
]
LEAKAGE_RE = [
    re.compile(r"\btraceback\.format_exc\(\)", re.IGNORECASE),
    re.compile(r"\bformat_exc\(\)", re.IGNORECASE),
    re.compile(r"\bstr\(exc\)\b", re.IGNORECASE),
    re.compile(r"\brepr\(exc\)\b", re.IGNORECASE),
    re.compile(r"\bstack\s*trace\b", re.IGNORECASE),
    re.compile(r"\bsql(state|error)?\b", re.IGNORECASE),
]
OUTWARD_HINT_RE = re.compile(
    r"(JSONResponse|HttpException|HTTPException|res\.status|return\s+\{[^}]{0,200}(detail|message|error)|problem\+json)",
    re.IGNORECASE,
)
NUMERIC_CODE_RE = re.compile(r'["\']code["\']\s*[:=]\s*\d{3,}', re.IGNORECASE)
ASYNC_STRUCTURED_RE = re.compile(r"(contentType\s*:\s*application/problem\+json|payload[^;\n]{0,80}(code|type|detail)|success/error union)", re.IGNORECASE)
DOC_CLAIM_RE = re.compile(r"(problem\+json|trace_id|error catalog|generated types?)", re.IGNORECASE)
CI_GUARD_RE = re.compile(r"(error[_-]?catalog|generated.*error|problem.*schema|codegen)", re.IGNORECASE)
CODEGEN_HINT_RE = re.compile(r"(generated by|openapi-generator|datamodel-codegen|quicktype|as const|Literal\[|enum\s+[A-Za-z_]+Error)", re.IGNORECASE)


@dataclass
class Finding:
    id: str
    category: str
    severity: str
    confidence: str
    scope: str
    title: str
    path: str
    line: int
    evidence_summary: str
    decision: str
    recommended_change_shape: str
    validation_checks: list[str]
    merge_gate: str
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class GateState:
    name: str
    status: str
    severity_bias: str
    summary: str

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scan a repo for error-governance drift.")
    parser.add_argument("--repo", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--report-out", default=None)
    parser.add_argument("--agent-brief-out", default=None)
    return parser.parse_args()


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def iter_files(root: Path) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [item for item in dirnames if item not in SKIP_DIRS]
        for filename in filenames:
            path = Path(dirpath) / filename
            if path.suffix.lower() in TEXT_EXTS:
                yield path


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def rel(path: Path, repo: Path) -> str:
    return path.relative_to(repo).as_posix()


def line_snippet(lines: list[str], line_no: int) -> str:
    if 1 <= line_no <= len(lines):
        return lines[line_no - 1].strip()[:240]
    return ""


def first_match(lines: list[str], patterns: Iterable[re.Pattern[str]]) -> tuple[int, str] | None:
    for idx, line in enumerate(lines, start=1):
        if any(pattern.search(line) for pattern in patterns):
            return idx, line.strip()[:240]
    return None


def has_any(text: str, patterns: Iterable[re.Pattern[str]]) -> bool:
    return any(pattern.search(text) for pattern in patterns)


def add_finding(findings: list[Finding], seen: set[tuple[str, str, int, str]], finding: Finding) -> None:
    key = (finding.category, finding.path, finding.line, finding.title)
    if key in seen:
        return
    seen.add(key)
    findings.append(finding)


def make_finding(
    category: str,
    severity: str,
    confidence: str,
    scope: str,
    title: str,
    path: str,
    line: int,
    evidence_summary: str,
    decision: str,
    recommended_change_shape: str,
    validation_checks: list[str],
    merge_gate: str,
    notes: str = "",
) -> Finding:
    return Finding(
        id="",
        category=category,
        severity=severity,
        confidence=confidence,
        scope=scope,
        title=title,
        path=path,
        line=line,
        evidence_summary=evidence_summary,
        decision=decision,
        recommended_change_shape=recommended_change_shape,
        validation_checks=validation_checks,
        merge_gate=merge_gate,
        notes=notes,
    )


def summarize_actions(findings: list[Finding]) -> list[str]:
    categories = {finding.category for finding in findings}
    actions: list[str] = []
    if {"universal-problem-gap", "field-pattern-gap", "http-mapping-gap"} & categories:
        actions.append("Extract one shared public error schema and align HTTP responses on `application/problem+json` plus stable top-level fields.")
    if {"text-branching", "numeric-or-vague-code", "ssot-missing"} & categories:
        actions.append("Replace message-text branching with one versioned error-code catalog and structured `code` handling.")
    if {"leakage-risk", "no-global-handler", "traceability-gap"} & categories:
        actions.append("Add one outward-facing boundary translator that strips internals and injects traceability fields consistently.")
    if {"codegen-drift", "ci-gate-missing"} & categories:
        actions.append("Generate Python / TypeScript error artifacts from the same source of truth and add drift checks in CI.")
    if {"async-contract-gap"} & categories:
        actions.append("Make async error payloads structurally explicit instead of relying on plain strings or implicit failure semantics.")
    if not actions:
        actions.append("Keep the current error contract explicit and resist reintroducing ad-hoc JSON error shapes.")
    return actions[:3]


def gate_state(name: str, status: str, severity_bias: str, summary: str) -> GateState:
    return GateState(name=name, status=status, severity_bias=severity_bias, summary=summary)


def render_human_report(summary: dict[str, Any]) -> str:
    findings = sorted(
        summary["findings"],
        key=lambda item: ({"critical": 0, "high": 1, "medium": 2, "low": 3}[item["severity"]], item["path"], item["line"]),
    )
    top_findings = findings[:6]
    top_actions = summary.get("top_actions") or []

    runtime_vs_openapi = "OpenAPI surfaces were found." if summary["coverage"]["openapi_surfaces"] else "No OpenAPI surface was detected."
    if any(item["category"] == "http-mapping-gap" for item in findings):
        runtime_vs_openapi += " HTTP mapping evidence is weaker than the public contract surface."

    runtime_vs_async = "AsyncAPI surfaces were found." if summary["coverage"]["asyncapi_surfaces"] else "No AsyncAPI surface was detected."
    if any(item["category"] == "async-contract-gap" for item in findings):
        runtime_vs_async += " Async error payload discipline is weaker than it should be."

    schema_vs_codegen = "Generated type surfaces were found." if summary["coverage"]["generated_type_surfaces"] else "No generated type surface was found."
    if any(item["category"] == "codegen-drift" for item in findings):
        schema_vs_codegen += " Runtime and generated artifacts do not currently look governed by one source of truth."

    catalog_vs_docs = "Catalog surfaces were found." if summary["coverage"]["catalogs_found"] else "No dedicated error catalog was found."
    if any(item["category"] == "docs-runtime-drift" for item in findings):
        catalog_vs_docs += " Documentation claims exceed visible runtime evidence."

    lines = [
        "# Error Governance Hardgate Report",
        "",
        "## 1. Executive summary",
        f"- Overall verdict: `{summary['overall_verdict']}`",
        f"- One-line diagnosis: `{summary['summary_line']}`",
        f"- Repo root: `{summary['repo_root']}`",
        f"- dependency_status: `{summary['dependency_status']}`",
        "",
        "## 2. Gate map",
        "",
    ]
    for gate in summary["gate_states"]:
        lines.extend([
            f"### {gate['name']}",
            f"- Status: `{gate['status']}`",
            f"- Severity bias: `{gate.get('severity_bias', 'medium')}`",
            f"- Summary: {gate['summary']}",
            "",
        ])

    lines.extend(["## 3. Highest-risk findings", ""])
    if not top_findings:
        lines.append("No high-signal error-governance findings were detected by the bundled baseline.")
    else:
        for finding in top_findings:
            plain = {
                "text-branching": "系统把给人看的错误文案，当成了给程序分支的稳定接口。",
                "leakage-risk": "系统把内部实现细节直接暴露给外部调用方了。",
                "no-global-handler": "系统没有一个可信的统一出口来把内部错误翻译成稳定公共契约。",
                "ssot-missing": "公共错误码没有唯一真源，迟早会多处漂移。",
                "codegen-drift": "多语言错误类型不是从同一真源生成出来的，维护会分叉。",
                "http-mapping-gap": "公共 HTTP 契约和实际错误输出格式没有真正对齐。",
                "async-contract-gap": "异步错误没有被建模成清晰的结构化契约。",
            }.get(finding["category"], "公共错误契约存在可持续性或一致性风险。")
            lines.extend([
                f"### {finding['title']}",
                f"- Category: `{finding['category']}`",
                f"- Severity: `{finding['severity']}`",
                f"- Confidence: `{finding['confidence']}`",
                f"- Evidence: `{finding['path']}:{finding['line']}`",
                "",
                "**是什么**",
                finding["evidence_summary"],
                "",
                "**为什么重要**",
                plain,
                "",
                "**建议做什么**",
                finding["recommended_change_shape"],
                "",
                "**给非程序员的人话解释**",
                plain,
                "",
            ])

    lines.extend([
        "## 4. Where the contract splits or drifts",
        f"- runtime vs OpenAPI: {runtime_vs_openapi}",
        f"- runtime vs AsyncAPI: {runtime_vs_async}",
        f"- shared schema vs generated types: {schema_vs_codegen}",
        f"- catalog vs docs: {catalog_vs_docs}",
        "",
        "## 5. What looks safe to harden now",
    ])
    for action in top_actions or ["No immediate low-risk hardening action was identified."]:
        lines.append(f"- {action}")

    lines.extend([
        "",
        "## 6. What still needs design decisions",
    ])
    design_needed = [
        finding for finding in findings
        if finding["category"] in {"async-contract-gap", "ssot-missing", "codegen-drift"}
    ]
    if not design_needed:
        lines.append("- No additional design-only blocker stood out beyond the ordered hardening work.")
    else:
        for finding in design_needed[:3]:
            lines.append(f"- {finding['title']}")

    lines.extend([
        "",
        "## 7. Ordered action plan",
        "",
        "### 现在就做",
        f"- {top_actions[0] if top_actions else 'Preserve the current contract shape and avoid ad-hoc error JSON changes.'}",
        "",
        "### 下一步",
        f"- {top_actions[1] if len(top_actions) > 1 else 'Add contract tests that pin the public error object.'}",
        "",
        "### 之后再做",
        f"- {top_actions[2] if len(top_actions) > 2 else 'Add CI drift checks once the public error surface is centralized.'}",
        "",
        "## 8. What this repo is teaching AI to do wrong",
        "- \"Treat the error message as the API.\"",
        "- \"Invent a fresh error JSON shape in each handler.\"",
        "- \"Maintain public error codes in multiple places and hope they stay aligned.\"",
    ])
    return "\n".join(lines) + "\n"


def render_agent_brief(summary: dict[str, Any]) -> str:
    findings = sorted(
        summary["findings"],
        key=lambda item: ({"critical": 0, "high": 1, "medium": 2, "low": 3}[item["severity"]], item["path"], item["line"]),
    )[:8]
    actions = summary.get("top_actions") or []
    lines = [
        "# Error Governance Hardgate Agent Brief",
        "",
        "Use short, hard, decision-level language. Do not write long tutorials.",
        "",
        "## Context",
        f"- overall_verdict: `{summary['overall_verdict']}`",
        f"- repo_root: `{summary['repo_root']}`",
        "",
        "## Ordered actions",
        f"1. `{actions[0] if actions else 'Centralize the public error contract before patching symptoms.'}`",
        f"2. `{actions[1] if len(actions) > 1 else 'Add contract tests that pin the public error object and stable business codes.'}`",
        f"3. `{actions[2] if len(actions) > 2 else 'Add CI drift checks once the contract source of truth is centralized.'}`",
        "",
        "## Findings",
        "",
        "```yaml",
    ]
    if not findings:
        lines.extend([
            "- id: egh-000",
            "  category: healthy-baseline",
            "  severity: low",
            "  confidence: medium",
            "  scope: repo",
            "  title: No bundled high-signal error-governance drift was found",
            "  evidence_summary: Keep the current public error contract explicit and stable.",
            "  decision: preserve-shape",
            "  recommended_change_shape: Avoid ad-hoc public error JSON changes and keep contract tests in place.",
            "  validation_checks:",
            "    - Rerun the wrapper after significant API error-surface changes.",
            "  merge_gate: watch",
            "  notes: Bundled scan is heuristic, not a full proof.",
        ])
    else:
        for finding in findings:
            lines.extend([
                f"- id: {finding['id']}",
                f"  category: {finding['category']}",
                f"  severity: {finding['severity']}",
                f"  confidence: {finding['confidence']}",
                f"  scope: {finding['scope']}",
                f"  title: {finding['title']}",
                f"  evidence_summary: {json.dumps(finding['evidence_summary'], ensure_ascii=False)}",
                f"  decision: {finding['decision']}",
                f"  recommended_change_shape: {json.dumps(finding['recommended_change_shape'], ensure_ascii=False)}",
                "  validation_checks:",
            ])
            for check in finding["validation_checks"]:
                lines.append(f"    - {check}")
            lines.extend([
                f"  merge_gate: {finding['merge_gate']}",
                f"  notes: {json.dumps(finding.get('notes', ''), ensure_ascii=False)}",
            ])
    lines.extend(["```", ""])
    return "\n".join(lines)


def analyze_repo(repo: Path) -> dict[str, Any]:
    findings: list[Finding] = []
    seen: set[tuple[str, str, int, str]] = set()

    languages: set[str] = set()
    frameworks: set[str] = set()
    protocols: set[str] = set()

    relevant_files: set[str] = set()
    openapi_files: set[str] = set()
    asyncapi_files: set[str] = set()
    catalog_files: set[str] = set()
    generated_files: set[str] = set()
    handler_files: set[str] = set()
    docs_files: set[str] = set()

    files_scanned = 0
    core_field_hits: Counter[str] = Counter()
    extension_hits: Counter[str] = Counter()
    doc_claims = 0
    code_usage_found = False
    global_handler_found = False
    ci_guard_found = False
    async_structured_found = False
    problem_media_found = False

    for path in iter_files(repo):
        files_scanned += 1
        rel_path = rel(path, repo)
        suffix = path.suffix.lower()
        text = read_text(path)
        if not text:
            continue
        lines = text.splitlines()
        lower_path = rel_path.lower()

        if suffix in {".py", ".pyi"}:
            languages.add("python")
        elif suffix in {".ts", ".tsx"}:
            languages.add("typescript")
        elif suffix in {".js", ".jsx", ".mjs", ".cjs"}:
            languages.add("javascript")

        for framework, pattern in FRAMEWORK_RE.items():
            if pattern.search(text):
                frameworks.add(framework)

        if suffix in DOC_EXTS:
            docs_files.add(rel_path)
            if DOC_CLAIM_RE.search(text):
                doc_claims += 1

        if OPENAPI_RE.search(rel_path) or (suffix in {".yaml", ".yml", ".json"} and OPENAPI_RE.search(text[:10000])):
            openapi_files.add(rel_path)
            relevant_files.add(rel_path)
            protocols.add("http")

        if ASYNCAPI_RE.search(rel_path) or (suffix in {".yaml", ".yml", ".json"} and ASYNCAPI_RE.search(text[:10000])):
            asyncapi_files.add(rel_path)
            relevant_files.add(rel_path)
            protocols.add("async")

        if PATH_SURFACE_RE["catalog"].search(rel_path):
            catalog_files.add(rel_path)
            relevant_files.add(rel_path)

        if PATH_SURFACE_RE["generated"].search(rel_path) and CODEGEN_HINT_RE.search(text[:12000]):
            generated_files.add(rel_path)
            relevant_files.add(rel_path)

        if suffix in CODE_EXTS and PATH_SURFACE_RE["handler"].search(rel_path):
            handler_files.add(rel_path)
            relevant_files.add(rel_path)
            protocols.add("http")

        if PATH_SURFACE_RE["schema"].search(rel_path) or PROBLEM_DETAILS_RE.search(text[:12000]):
            relevant_files.add(rel_path)

        if PROBLEM_MEDIA_RE.search(text):
            problem_media_found = True
        for key, pattern in CORE_FIELD_RE.items():
            if pattern.search(text):
                core_field_hits[key] += 1
        for key, pattern in EXTENSION_FIELD_RE.items():
            if pattern.search(text):
                extension_hits[key] += 1
        if EXTENSION_FIELD_RE["code"].search(text):
            code_usage_found = True
        if ASYNC_STRUCTURED_RE.search(text):
            async_structured_found = True
        if any(pattern.search(text) for pattern in GLOBAL_HANDLER_RE):
            global_handler_found = True
        if ".github/workflows/" in lower_path or lower_path.endswith(("pre-commit-config.yaml", "pre-commit-config.yml")):
            if CI_GUARD_RE.search(text):
                ci_guard_found = True

        if suffix in CODE_EXTS and "/tests/" not in f"/{lower_path}" and "test_" not in path.name.lower():
            text_branch = first_match(lines, TEXT_BRANCH_RE)
            if text_branch:
                line_no, snippet = text_branch
                add_finding(
                    findings,
                    seen,
                    make_finding(
                        "text-branching",
                        "critical",
                        "high",
                        rel_path,
                        "Business control flow depends on message text",
                        rel_path,
                        line_no,
                        snippet,
                        "replace-text-branching",
                        "Replace message-text branching with stable `code` handling and one shared error contract.",
                        [
                            "Prove branch logic uses stable `code` values instead of `detail`, `message`, or `title`.",
                            "Add tests showing copy changes do not break control flow.",
                        ],
                        "block-now",
                    ),
                )

            if OUTWARD_HINT_RE.search(text):
                leakage_match = first_match(lines, LEAKAGE_RE)
                if leakage_match:
                    line_no, snippet = leakage_match
                    add_finding(
                        findings,
                        seen,
                        make_finding(
                            "leakage-risk",
                            "critical",
                            "high",
                            rel_path,
                            "Outward-facing error path appears to leak internal detail",
                            rel_path,
                            line_no,
                            snippet,
                            "strip-internals",
                            "Normalize outward error responses at the boundary and keep stack/database detail in internal logs only.",
                            [
                                "Verify no public error response exposes traceback, SQL detail, or raw exception text.",
                                "Add one boundary test that pins the public error object for representative failures.",
                            ],
                            "block-now",
                        ),
                    )

            numeric_code = first_match(lines, [NUMERIC_CODE_RE])
            if numeric_code:
                line_no, snippet = numeric_code
                add_finding(
                    findings,
                    seen,
                    make_finding(
                        "numeric-or-vague-code",
                        "high",
                        "medium",
                        rel_path,
                        "Business identity appears to rely on numeric error codes",
                        rel_path,
                        line_no,
                        snippet,
                        "stabilize-codes",
                        "Replace numeric or weak public codes with stable, documented string keys backed by one catalog.",
                        [
                            "Verify public clients branch on stable string codes, not numeric trivia.",
                            "Add uniqueness checks for public `code` values in the source of truth.",
                        ],
                        "fix-before-release",
                    ),
                )

    public_surfaces = bool(openapi_files or asyncapi_files or handler_files)
    typed_languages = languages & {"python", "typescript", "javascript"}
    multi_language_public = len(typed_languages) >= 2
    core_problem_count = sum(int(core_field_hits[key] > 0) for key in CORE_FIELD_RE)
    extension_count = sum(int(extension_hits[key] > 0) for key in ("code", "trace_id", "timestamp", "service"))
    coherent_problem_shape = (
        public_surfaces
        and problem_media_found
        and core_problem_count >= 3
        and code_usage_found
        and global_handler_found
    )

    if public_surfaces and (not problem_media_found and core_problem_count < 3):
        add_finding(
            findings,
            seen,
            make_finding(
                "universal-problem-gap",
                "high",
                "medium",
                "repo",
                "No coherent shared Problem Details-style public error shape is visible",
                ".",
                1,
                "Public API or handler surfaces exist, but shared Problem Details evidence is weak or missing.",
                "extract-shared-problem-schema",
                "Extract one shared public error schema and route outward responses through it.",
                [
                    "Verify representative HTTP errors share one object shape.",
                    "Verify the same top-level fields appear in contracts and runtime handlers.",
                ],
                "fix-before-release",
            ),
        )

    if public_surfaces and extension_hits["code"] == 0:
        add_finding(
            findings,
            seen,
            make_finding(
                "field-pattern-gap",
                "high",
                "medium",
                "repo",
                "Public error shape lacks stable structured business codes",
                ".",
                1,
                "Problem-shape or outward error evidence exists, but stable top-level `code` evidence is missing.",
                "introduce-structured-code",
                "Add one stable top-level `code` field and migrate clients away from message parsing.",
                [
                    "Verify public error examples and runtime handlers both include `code`.",
                    "Add tests showing localization or copy changes do not change branch behavior.",
                ],
                "fix-before-release",
            ),
        )

    if public_surfaces and extension_count < 4:
        add_finding(
            findings,
            seen,
            make_finding(
                "traceability-gap",
                "medium",
                "medium",
                "repo",
                "Public error responses do not show consistent traceability metadata",
                ".",
                1,
                "Visible public error-contract evidence is missing some of `trace_id`, `timestamp`, or `service`.",
                "inject-traceability",
                "Inject traceability metadata consistently at the public error boundary instead of ad-hoc per handler.",
                [
                    "Verify public errors carry `trace_id`, `timestamp`, and `service` consistently.",
                ],
                "fix-next",
            ),
        )

    if openapi_files and not problem_media_found:
        add_finding(
            findings,
            seen,
            make_finding(
                "http-mapping-gap",
                "high",
                "medium",
                "http",
                "OpenAPI surface lacks clear `application/problem+json` evidence",
                ".",
                1,
                "OpenAPI-like surfaces exist, but no `application/problem+json` evidence was found.",
                "align-http-contract",
                "Align public HTTP error responses and contracts on one `application/problem+json` shape.",
                [
                    "Verify OpenAPI documents the same error media type that runtime handlers emit.",
                ],
                "fix-before-release",
            ),
        )

    if asyncapi_files and not async_structured_found:
        add_finding(
            findings,
            seen,
            make_finding(
                "async-contract-gap",
                "high",
                "medium",
                "async",
                "Async error payload discipline is not clearly modeled",
                ".",
                1,
                "AsyncAPI or event surfaces were found, but structured async error-payload evidence is weak.",
                "model-async-errors",
                "Model async error payloads as explicit structured contracts instead of plain strings or implicit failure semantics.",
                [
                    "Verify async error messages carry structured payload fields such as `code`, `type`, and `detail`.",
                ],
                "fix-before-release",
            ),
        )

    if handler_files and not global_handler_found:
        add_finding(
            findings,
            seen,
            make_finding(
                "no-global-handler",
                "high",
                "medium",
                "runtime",
                "No credible global error translation layer is visible",
                ".",
                1,
                "Handler surfaces were found, but no clear global exception boundary was detected.",
                "add-boundary-handler",
                "Introduce one outward-facing error boundary that normalizes exceptions into the shared public contract.",
                [
                    "Verify representative failures are translated by one boundary layer instead of ad-hoc handler logic.",
                ],
                "fix-before-release",
            ),
        )

    if public_surfaces and code_usage_found and not catalog_files:
        ssot_severity = "high" if multi_language_public or asyncapi_files else "medium"
        ssot_merge_gate = "fix-before-release" if ssot_severity == "high" else "fix-next"
        ssot_title = (
            "Public error codes do not appear to have one dedicated source of truth"
            if ssot_severity == "high"
            else "Structured public error codes exist, but the source of truth is still implicit"
        )
        ssot_evidence = (
            "Structured code usage was detected, but no dedicated error catalog surface was found across multiple public surfaces."
            if ssot_severity == "high"
            else "Structured code usage was detected, but no dedicated catalog surface was found. In a single-language repo with a coherent boundary this is debt, not immediate proof of drift."
        )
        add_finding(
            findings,
            seen,
            make_finding(
                "ssot-missing",
                ssot_severity,
                "medium",
                "repo",
                ssot_title,
                ".",
                1,
                ssot_evidence,
                "create-catalog",
                "Create one versioned error catalog and treat it as the source of truth for public codes and types.",
                [
                    "Verify every public code is declared in one catalog.",
                    "Verify handlers and docs derive from the same catalog.",
                ],
                ssot_merge_gate,
                notes="This is a stronger blocker when multiple languages or protocols expose the same public error contract.",
            ),
        )

    if {"python", "typescript"} <= languages and not generated_files:
        add_finding(
            findings,
            seen,
            make_finding(
                "codegen-drift",
                "high",
                "medium",
                "repo",
                "Multi-language error artifacts do not appear to be generated from one source",
                ".",
                1,
                "Python and TypeScript surfaces were detected, but no generated error-artifact surface was found.",
                "restore-codegen",
                "Generate multi-language error types from the same catalog instead of maintaining parallel public code lists.",
                [
                    "Verify Python and TypeScript error artifacts are regenerated from one source of truth.",
                ],
                "fix-before-release",
            ),
        )

    if catalog_files and not ci_guard_found:
        add_finding(
            findings,
            seen,
            make_finding(
                "ci-gate-missing",
                "medium",
                "low",
                "repo",
                "Catalog or generated artifact drift is not visibly gated in CI",
                ".",
                1,
                "Catalog-like surfaces were found, but no visible CI/pre-commit guard for error-contract drift was detected.",
                "add-drift-check",
                "Add CI or review checks that fail on catalog uniqueness, schema drift, or generated-artifact staleness.",
                [
                    "Verify a PR fails when the public error catalog and generated artifacts drift apart.",
                ],
                "fix-next",
            ),
        )

    if doc_claims and public_surfaces and not problem_media_found and not global_handler_found:
        add_finding(
            findings,
            seen,
            make_finding(
                "docs-runtime-drift",
                "medium",
                "low",
                "repo",
                "Documentation claims look stronger than visible runtime error-governance evidence",
                ".",
                1,
                "Documentation mentions structured error-governance signals, but runtime evidence remains weak.",
                "close-doc-runtime-gap",
                "Either align runtime behavior with the documented contract or reduce unsupported claims in docs/examples.",
                [
                    "Verify runtime behavior matches the documented public error contract.",
                ],
                "watch",
            ),
        )

    severity_counts = Counter({"critical": 0, "high": 0, "medium": 0, "low": 0})
    for finding in findings:
        severity_counts[finding.severity] += 1

    categories = {finding.category for finding in findings}
    gate_states = [
        gate_state(
            "universal-problem-shape",
            "fail" if {"universal-problem-gap", "field-pattern-gap"} & categories else ("pass" if public_surfaces else "not-applicable"),
            "high",
            "One shared public error object is not yet evident." if {"universal-problem-gap", "field-pattern-gap"} & categories else (
                "Public error shape looks coherent enough for the bundled baseline." if public_surfaces else "No public API or event surface was detected."
            ),
        ),
        gate_state(
            "stable-business-codes",
            "fail" if {"text-branching", "numeric-or-vague-code"} & categories else (
                "watch" if "ssot-missing" in categories else ("pass" if code_usage_found or catalog_files else "watch")
            ),
            "critical" if "text-branching" in categories else "high",
            "Structured business codes are not governed durably enough." if {"text-branching", "numeric-or-vague-code"} & categories else (
                "Structured business codes exist, but the source of truth is still implicit." if "ssot-missing" in categories else "No top-level stable-code failure was detected by the bundled baseline."
            ),
        ),
        gate_state(
            "protocol-alignment",
            "fail" if {"http-mapping-gap", "async-contract-gap"} & categories else ("pass" if openapi_files or asyncapi_files else "not-applicable"),
            "high",
            "Protocol contracts drift from the desired shared error model." if {"http-mapping-gap", "async-contract-gap"} & categories else (
                "Visible protocol surfaces do not show a high-signal alignment failure." if openapi_files or asyncapi_files else "No protocol contract surface was detected."
            ),
        ),
        gate_state(
            "boundary-safety",
            "fail" if {"leakage-risk", "no-global-handler"} & categories else ("watch" if "traceability-gap" in categories else ("pass" if public_surfaces else "not-applicable")),
            "critical" if "leakage-risk" in categories else "high",
            "Outward-facing boundary safety is currently too weak." if {"leakage-risk", "no-global-handler"} & categories else (
                "Traceability evidence is incomplete." if "traceability-gap" in categories else (
                    "No high-signal outward boundary failure was detected." if public_surfaces else "No outward boundary surface was detected."
                )
            ),
        ),
        gate_state(
            "ssot-and-codegen",
            "fail" if "codegen-drift" in categories or ("ssot-missing" in categories and multi_language_public) else (
                "watch" if {"ssot-missing", "ci-gate-missing"} & categories else "pass"
            ),
            "high",
            "Catalog/codegen governance is currently too weak." if "codegen-drift" in categories or ("ssot-missing" in categories and multi_language_public) else (
                "A dedicated source of truth or drift guard is still missing." if {"ssot-missing", "ci-gate-missing"} & categories else "No high-signal SSOT/codegen failure was detected."
            ),
        ),
    ]

    if not public_surfaces and not catalog_files and not generated_files:
        overall_verdict = "not-applicable"
        summary_line = "No public error-contract, schema, catalog, or generated-type surface was detected for this audit."
    elif severity_counts["critical"] > 0 or severity_counts["high"] >= 3:
        overall_verdict = "blocked"
        summary_line = "The repo shows high-signal public error-contract drift that should block trust in the current outward error surface."
    elif severity_counts["high"] > 0 or any(gate.status == "fail" for gate in gate_states):
        overall_verdict = "partial"
        summary_line = "The repo has meaningful error-governance gaps: some structure exists, but the public contract is not yet trustworthy end to end."
    elif coherent_problem_shape and "ssot-missing" in categories and len(findings) == 1:
        overall_verdict = "watch"
        summary_line = "The public error surface looks coherent, but the source of truth for codes is still implicit and should be centralized before the contract grows."
    elif findings:
        overall_verdict = "watch"
        summary_line = "The repo shows moderate error-governance debt, but the bundled baseline did not find a top-level blocker."
    else:
        overall_verdict = "healthy"
        summary_line = "No bundled high-signal error-governance drift was found."

    top_actions = summarize_actions(findings)
    summary = {
        "schema_version": SCHEMA_VERSION,
        "skill": SKILL,
        "generated_at": utc_now(),
        "repo_root": str(repo.resolve()),
        "overall_verdict": overall_verdict,
        "summary_line": summary_line,
        "language_profile": {
            "languages": sorted(languages),
            "frameworks": sorted(frameworks),
            "protocols": sorted(protocols),
        },
        "coverage": {
            "files_scanned": files_scanned,
            "relevant_files": len(relevant_files),
            "openapi_surfaces": len(openapi_files),
            "asyncapi_surfaces": len(asyncapi_files),
            "catalogs_found": len(catalog_files),
            "generated_type_surfaces": len(generated_files),
        },
        "severity_counts": {key: int(severity_counts[key]) for key in ("critical", "high", "medium", "low")},
        "gate_states": [gate.to_dict() for gate in gate_states],
        "scan_blockers": [],
        "findings": [],
        "top_actions": top_actions,
        "dependency_status": "ready",
        "bootstrap_actions": [],
        "dependency_failures": [],
    }
    for idx, finding in enumerate(findings, start=1):
        finding.id = f"egh-{idx:03d}"
        summary["findings"].append(finding.to_dict())
    return summary


def main() -> int:
    args = parse_args()
    repo = Path(args.repo).resolve()
    out_path = Path(args.out).resolve()
    if not repo.is_dir():
        raise SystemExit(f"Repository root does not exist or is not a directory: {repo}")

    summary = analyze_repo(repo)
    report = render_human_report(summary)
    brief = render_agent_brief(summary)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    report_path = Path(args.report_out).resolve() if args.report_out else out_path.with_name("error-governance-report.md")
    brief_path = Path(args.agent_brief_out).resolve() if args.agent_brief_out else out_path.with_name("error-governance-agent-brief.md")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    brief_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report, encoding="utf-8")
    brief_path.write_text(brief, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
